spring:
  application:
    name: scloud-eureka
  jackson:
      serialization:
        indent_output: true
  boot:
    admin:
      url: http://peer1:8090/
      auto-registration: true
      client:
        name: ${spring.application.name}

server:
  port: 1111

management:
  security:
    enabled: false

endpoints:
  health:
    sensitive: false

security:
  basic:
    enabled: false

eureka:
  instance:
    hostname: peer1
    instance-id: peer1:1111
    preferIpAddress: false
#    ip-address: 127.0.0.1
#    statusPageUrlPath: /info.html
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    metadata-map:
      cluster: scloud
  client:
    register-with-eureka: true
    fetch-registry: true
#    healthcheck:
#      enabled: true
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://peer2:1111/eureka/
  server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 60000

#logging:
#  level:
#    com:
#      netflix:
#        eureka: OFF
#        discovery: OFF

#eureka.instance.ip-address=${SERVICE_HOST_IP}
#eureka.instance.prefer-ip-address=true