spring:
  application:
    name: ${SERVICE_APPLICATION_NAME}
  jackson:
      serialization:
        indent_output: true
  boot:
    admin:
      url: http://${ADMIN_HOST_URL}:${ADMIN_HOST_PORT}/
      auto-registration: true
      client:
        name: ${spring.application.name}

server:
  port: ${SERVICE_HOST_PORT}

management:
  security:
    enabled: false

endpoints:
  health:
    sensitive: false

security:
  basic:
    enabled: false

eureka:
  instance:
    hostname: ${SERVICE_INSTANCE_NAME}
    instance-id: ${eureka.instance.hostname}:${server.port}
    preferIpAddress: false
#    ip-address: ${SERVICE_HOST_IP}
#    statusPageUrlPath: /info.html
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    metadata-map:
      cluster: scloud
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: ${EUREKA_SERVERS}
  server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 60000

#logging:
#  level:
#    com:
#      netflix:
#        eureka: OFF
#        discovery: OFF

#eureka.instance.ip-address=${SERVICE_HOST_IP}
#eureka.instance.prefer-ip-address=true