spring:
  application:
    name: ${SERVICE_APPLICATION_NAME}
  jackson:
      serialization:
        indent_output: true
  boot:
    admin:
      url: http://${eureka.instance.hostname}:${server.port}
      auto-registration: true
      client:
        name: ${spring.application.name}

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

server:
  port: ${SERVICE_HOST_PORT}

eureka:
  instance:
    preferIpAddress: false
    statusPageUrlPath: /info.html
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    metadata-map:
      cluster: scloud
    hostname: ${SERVICE_INSTANCE_NAME}
    instance-id: ${eureka.instance.hostname}:${server.port}
    ip-address: ${SERVICE_HOST_IP}
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: ${EUREKA_SERVERS}